import Head from 'next/head'
import Layout from '../hoc/Layout'
import HomePage from '../container/Home'

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Zakki Haris</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/favicon.png" />
        </Head>
        <div>
          <HomePage />
        </div>
      </Layout>

    </>
  )
}
